"""Incident report builders.

Renders a case (incident + linked conversations + IOC verdict trail) as a
shareable document. Two formats:

- Markdown: for pasting into tickets (TheHive, Jira, email).
- HTML: self-contained, print-optimized page — the analyst uses the browser's
  Print → Save as PDF for a hand-off artifact. No PDF library dependency.

All user/LLM content is escaped; assistant replies are rendered as
preformatted text rather than re-interpreting their markdown, so nothing in a
chat can inject markup into the report.
"""
from __future__ import annotations

import html
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


def _fmt_ts(iso: Optional[str]) -> str:
    if not iso:
        return "—"
    try:
        dt = datetime.fromisoformat(iso)
        return dt.strftime("%Y-%m-%d %H:%M UTC")
    except Exception:
        return iso


def _now_ts() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def build_incident_report_md(
    incident: Dict[str, Any],
    conversations: List[Dict[str, Any]],
    verdicts: List[Dict[str, Any]],
) -> str:
    """Markdown report. `conversations` are full conversation dicts (with
    `messages`); `verdicts` is the IOC verdict trail for those conversations."""
    inc = incident
    lines: List[str] = []
    lines.append(f"# {inc['case_number']} — {inc['title']}")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Case | {inc['case_number']} |")
    lines.append(f"| Severity | {inc['severity'].upper()} |")
    lines.append(f"| Status | {inc['status']} |")
    lines.append(f"| Verdict | {inc.get('verdict') or '—'} |")
    lines.append(f"| Opened | {_fmt_ts(inc.get('created_at'))} |")
    lines.append(f"| Closed | {_fmt_ts(inc.get('closed_at'))} |")
    lines.append(f"| Report generated | {_now_ts()} |")
    lines.append("")

    if inc.get("notes"):
        lines.append("## Analyst Notes")
        lines.append("")
        lines.append(inc["notes"])
        lines.append("")

    if verdicts:
        lines.append("## IOC Verdicts")
        lines.append("")
        lines.append("| IOC | Type | Verdict | Confidence | Recorded |")
        lines.append("|---|---|---|---|---|")
        for v in verdicts:
            lines.append(
                f"| `{v['ioc_value']}` | {v['ioc_type']} | {v.get('verdict') or '—'} "
                f"| {v.get('confidence') or '—'} | {_fmt_ts(v.get('created_at'))} |"
            )
        lines.append("")

    lines.append("## Investigation Timeline")
    lines.append("")
    if not conversations:
        lines.append("_No conversations linked to this case._")
        lines.append("")
    for conv in conversations:
        lines.append(f"### {conv.get('title') or 'Untitled investigation'}")
        lines.append("")
        lines.append(f"_Started {_fmt_ts(conv.get('created_at'))}_")
        lines.append("")
        for m in conv.get("messages", []):
            who = "Analyst" if m["role"] == "user" else "NullShift"
            lines.append(f"**{who}** — {_fmt_ts(m.get('created_at'))}")
            lines.append("")
            content = m.get("content") or ""
            if not isinstance(content, str):
                content = str(content)
            lines.append(content)
            lines.append("")
            lines.append("---")
            lines.append("")

    lines.append(f"_Generated by NullShift on {_now_ts()}_")
    return "\n".join(lines)


_SEV_COLORS = {
    "low": "#22c55e",
    "medium": "#eab308",
    "high": "#f97316",
    "critical": "#ef4444",
}

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{case_number} — {title}</title>
<style>
  :root {{ color-scheme: light; }}
  * {{ box-sizing: border-box; }}
  body {{
    font: 14px/1.55 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
    color: #1a2233; background: #f4f6fa; margin: 0; padding: 32px 16px;
  }}
  .page {{ max-width: 860px; margin: 0 auto; background: #fff;
          border: 1px solid #dde3ee; border-radius: 8px; padding: 40px 48px; }}
  h1 {{ font-size: 22px; margin: 0 0 4px; }}
  h2 {{ font-size: 15px; margin: 32px 0 10px; padding-bottom: 6px;
       border-bottom: 2px solid #e6ebf4; text-transform: uppercase;
       letter-spacing: .06em; color: #33415e; }}
  h3 {{ font-size: 14px; margin: 20px 0 4px; }}
  .subtitle {{ color: #5b6b8c; margin: 0 0 24px; font-size: 13px; }}
  .badges {{ margin: 12px 0 4px; }}
  .badge {{ display: inline-block; padding: 3px 10px; border-radius: 12px;
           font-size: 11px; font-weight: 700; letter-spacing: .05em;
           text-transform: uppercase; color: #fff; margin-right: 6px; }}
  table {{ border-collapse: collapse; width: 100%; margin: 8px 0 16px; font-size: 13px; }}
  th, td {{ text-align: left; padding: 6px 10px; border: 1px solid #e2e8f2; }}
  th {{ background: #f0f3f9; font-weight: 600; }}
  td.mono, code {{ font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; }}
  .msg {{ border: 1px solid #e2e8f2; border-radius: 6px; margin: 10px 0; overflow: hidden; }}
  .msg-head {{ padding: 6px 12px; font-size: 12px; font-weight: 600;
              background: #f0f3f9; color: #33415e; display: flex; justify-content: space-between; }}
  .msg-head .ts {{ font-weight: 400; color: #7183a6; }}
  .msg-body {{ padding: 10px 12px; white-space: pre-wrap; word-break: break-word;
              font-size: 13px; }}
  .msg.assistant .msg-head {{ background: #eaf6fb; color: #0a6a8a; }}
  .notes {{ background: #fffbe8; border: 1px solid #f0e2ad; border-radius: 6px;
           padding: 10px 14px; white-space: pre-wrap; }}
  .footer {{ margin-top: 36px; padding-top: 12px; border-top: 1px solid #e6ebf4;
            font-size: 11px; color: #8494b3; }}
  .print-btn {{ position: fixed; top: 16px; right: 16px; background: #0a6a8a;
               color: #fff; border: 0; border-radius: 6px; padding: 10px 18px;
               font-size: 13px; font-weight: 600; cursor: pointer; }}
  .print-btn:hover {{ background: #085570; }}
  .muted {{ color: #8494b3; }}
  @media print {{
    body {{ background: #fff; padding: 0; }}
    .page {{ border: 0; border-radius: 0; padding: 0; max-width: none; }}
    .print-btn {{ display: none; }}
    .msg {{ break-inside: avoid; }}
  }}
</style>
</head>
<body>
<button class="print-btn" onclick="window.print()">Print / Save as PDF</button>
<div class="page">
  <h1>{case_number} — {title}</h1>
  <p class="subtitle">NullShift SOC Incident Report · generated {generated}</p>
  <div class="badges">
    <span class="badge" style="background:{sev_color}">{severity}</span>
    <span class="badge" style="background:#33415e">{status}</span>
  </div>
  <table>
    <tr><th>Verdict</th><td>{verdict}</td></tr>
    <tr><th>Opened</th><td>{opened}</td></tr>
    <tr><th>Closed</th><td>{closed}</td></tr>
    <tr><th>Linked investigations</th><td>{conv_count}</td></tr>
  </table>
  {notes_html}
  {verdicts_html}
  <h2>Investigation Timeline</h2>
  {timeline_html}
  <div class="footer">Generated by NullShift on {generated}. Contents include
  AI-assisted analysis — verify critical findings against raw SIEM data.</div>
</div>
</body>
</html>"""


def build_incident_report_html(
    incident: Dict[str, Any],
    conversations: List[Dict[str, Any]],
    verdicts: List[Dict[str, Any]],
) -> str:
    inc = incident
    e = html.escape

    notes_html = ""
    if inc.get("notes"):
        notes_html = f"<h2>Analyst Notes</h2>\n<div class=\"notes\">{e(inc['notes'])}</div>"

    verdicts_html = ""
    if verdicts:
        rows = "\n".join(
            f"<tr><td class=\"mono\">{e(v['ioc_value'])}</td>"
            f"<td>{e(v['ioc_type'])}</td>"
            f"<td>{e(v.get('verdict') or '—')}</td>"
            f"<td>{e(v.get('confidence') or '—')}</td>"
            f"<td>{e(_fmt_ts(v.get('created_at')))}</td></tr>"
            for v in verdicts
        )
        verdicts_html = (
            "<h2>IOC Verdicts</h2>\n<table>"
            "<tr><th>IOC</th><th>Type</th><th>Verdict</th><th>Confidence</th><th>Recorded</th></tr>"
            f"{rows}</table>"
        )

    parts: List[str] = []
    if not conversations:
        parts.append('<p class="muted">No conversations linked to this case.</p>')
    for conv in conversations:
        parts.append(f"<h3>{e(conv.get('title') or 'Untitled investigation')}</h3>")
        parts.append(
            f'<p class="muted" style="margin:0 0 8px;font-size:12px">'
            f"Started {e(_fmt_ts(conv.get('created_at')))}</p>"
        )
        for m in conv.get("messages", []):
            role = m.get("role") or ""
            who = "Analyst" if role == "user" else "NullShift"
            cls = "assistant" if role != "user" else "user"
            content = m.get("content") or ""
            if not isinstance(content, str):
                content = str(content)
            parts.append(
                f'<div class="msg {cls}">'
                f'<div class="msg-head"><span>{who}</span>'
                f'<span class="ts">{e(_fmt_ts(m.get("created_at")))}</span></div>'
                f'<div class="msg-body">{e(content)}</div></div>'
            )
    timeline_html = "\n".join(parts)

    return _HTML_TEMPLATE.format(
        case_number=e(inc["case_number"]),
        title=e(inc["title"]),
        generated=e(_now_ts()),
        sev_color=_SEV_COLORS.get(inc["severity"], "#33415e"),
        severity=e(inc["severity"]),
        status=e(inc["status"]),
        verdict=e(inc.get("verdict") or "—"),
        opened=e(_fmt_ts(inc.get("created_at"))),
        closed=e(_fmt_ts(inc.get("closed_at"))),
        conv_count=len(conversations),
        notes_html=notes_html,
        verdicts_html=verdicts_html,
        timeline_html=timeline_html,
    )
